"""The Gherkin renderer (SS11.1).

Two things matter beyond "it produces text": the output must parse with
Cucumber's own parser, and the traceability that makes the tool trustworthy
must survive into comments without cluttering the sentences a human reads.
"""

from __future__ import annotations

import pytest

from server.renderers.gherkin import render_document, render_test_case
from tests import factories as f


def parse(text: str):
    parser = pytest.importorskip("gherkin.parser")
    return parser.Parser().parse(text)


def build_case(**kwargs):
    assertion = f.assertion(
        "asrt_001",
        "the confirmation banner appears",
        ev=f.evidence("Order confirmed", "tc_0447", "evt_027", "semantic_node"),
    )
    steps = kwargs.pop(
        "steps",
        [
            f.step(
                "step_001",
                'the tester adds "Blue Widget" to the cart',
                event_ids=["evt_012", "evt_013"],
                assertions=[],
            ),
            f.step(
                "step_002",
                "the tester submits the order form",
                event_ids=["evt_027"],
                assertions=[assertion],
            ),
        ],
    )
    return f.test_case(steps=steps, **kwargs)


# --------------------------------------------------------------------------
# it parses
# --------------------------------------------------------------------------


def test_the_rendered_feature_parses(capsys):
    text = render_test_case(build_case(), generated_on="2026-08-17")
    parse(text)
    print(text)


def test_a_case_with_everything_still_parses():
    case = build_case(
        tags=["checkout", "@smoke"],
        preconditions=[
            f.precondition("pre_001", 'the tester is signed in as "<<user_email_1>>"', ["evt_003"]),
            f.precondition("pre_002", "the cart is empty", ["evt_004"]),
        ],
        parameters=[f.parameter("user_email_1", "<<user_email_1>>", "email")],
        omitted=[f.omitted_segment("seg_004", "exploratory", 3, "browsed the reports page")],
    )
    case.steps[0].escalation = "I could not tell whether the export finished - did a file download?"
    case.steps[0].confidence = "low"
    case.steps[1].selectorHints = [f.selector_hint("testId", '[data-testid="submit"]', "high")]

    text = render_test_case(case, generated_on="2026-08-17")
    parse(text)


def test_multiline_text_cannot_break_the_file():
    # Gherkin is line-oriented, so a newline inside a step would produce a file
    # that no longer parses.
    case = build_case(
        steps=[f.step("step_001", "the tester does\nsomething\n\nover lines", assertions=[])]
    )
    text = render_test_case(case)
    parse(text)
    assert "the tester does something over lines" in text


# --------------------------------------------------------------------------
# what a reader sees
# --------------------------------------------------------------------------


def test_the_header_says_where_this_came_from():
    case = build_case(objective="verify that orders over EUR500 require approval")
    text = render_test_case(case, generated_on="2026-08-17")

    assert text.startswith("# Generated by aitc-rem from recording rec_test01 - 2026-08-17")
    assert "# Objective: verify that orders over EUR500 require approval" in text


def test_evidence_travels_in_comments_not_in_step_text():
    text = render_test_case(build_case())
    lines = text.splitlines()

    step_line = next(ln for ln in lines if "submits the order form" in ln)
    assert "evt_027" not in step_line, "traceability must not clutter the sentence"

    # But it has to be there, one line down: this is what makes an assertion
    # auditable per sentence (SS3.2).
    evidence = next(ln for ln in lines if "# evidence:" in ln)
    assert "evt_027" in evidence
    assert "tc_0447" in evidence
    assert "Order confirmed" in evidence


def test_selectors_stay_in_comments():
    case = build_case()
    case.steps[1].selectorHints = [f.selector_hint("css", "button.submit", "low")]
    text = render_test_case(case)

    step_line = next(ln for ln in text.splitlines() if "submits the order form" in ln)
    assert "button.submit" not in step_line
    assert "# selector (css): button.submit" in text


def test_preconditions_become_a_background_block():
    case = build_case(
        preconditions=[
            f.precondition("pre_001", 'the tester is signed in as "<<user_email_1>>"', ["evt_003"]),
            f.precondition("pre_002", "the cart is empty", ["evt_004"]),
        ]
    )
    text = render_test_case(case)
    parse(text)

    assert "Background:" in text
    assert 'Given the tester is signed in as "<<user_email_1>>"' in text
    assert "And the cart is empty" in text


def test_omitted_work_is_shown_rather_than_hidden():
    # A verbatim transcript is unusable; silent deletion is untrustworthy. The
    # marker is the third option (SS9.3).
    case = build_case(
        omitted=[f.omitted_segment("seg_004", "exploratory", 3, "browsed the reports page")]
    )
    text = render_test_case(case)

    assert "3 exploratory action(s) omitted" in text
    assert "browsed the reports page" in text
    assert "See the review UI." in text


def test_a_step_needing_review_is_marked():
    case = build_case()
    case.steps[0].confidence = "low"
    case.steps[1].escalation = "did a file download?"
    text = render_test_case(case)

    assert "# Steps marked !! need human review." in text
    assert text.count("!!") >= 3  # the legend plus both steps
    assert "# ?? did a file download?" in text


def test_fidelity_flags_reach_the_reader():
    case = build_case()
    case.steps[0].fidelity = ["canvas_interaction"]
    text = render_test_case(case)
    assert "!canvas_interaction" in text


def test_rejected_assertions_are_not_rendered():
    # The review UI's accept/reject is the final gate; a rejected candidate is
    # not part of the test case.
    case = build_case()
    case.steps[1].assertions[0].accepted = False
    text = render_test_case(case)

    assert "the confirmation banner appears" not in text
    parse(text)


def test_coverage_suggestions_are_quarantined():
    # SS9.8 -- never rendered as steps, never exported as test cases, always
    # labelled unverified.
    case = build_case(
        suggestions=[
            f.coverage_suggestion(
                "sug_001",
                "The email field has type=email; an invalid-email path is untested.",
                "validation_path",
            )
        ]
    )
    text = render_test_case(case)
    parse(text)

    assert "UNVERIFIED" in text
    suggestion_line = next(ln for ln in text.splitlines() if "invalid-email" in ln)
    assert suggestion_line.strip().startswith("#")


def test_parameters_are_listed_for_the_person_who_runs_the_test():
    case = build_case(parameters=[f.parameter("user_email_1", "<<user_email_1>>", "email")])
    text = render_test_case(case)
    assert "<<user_email_1>>" in text
    assert "supply real values before running" in text


def test_a_document_renders_every_test_case():
    document = f.ir_document(test_cases=[build_case(), build_case(ident="tc_case_002")])
    rendered = render_document(document)

    assert set(rendered) == {"tc_case_001", "tc_case_002"}
    for text in rendered.values():
        parse(text)
