"""Gherkin renderer (SS11.1).

One of three renderers over the same IR -- no format is second-class, and a
fourth output means writing a renderer rather than touching the pipeline
(SS10).

    "Selectors live in comments and IR metadata, not in step text -- the
     feature file stays human-readable while retaining what automation needs
     later."
"""

from __future__ import annotations

from server.models import IRDocument, Step, TestCaseIR

INDENT = "  "
GENERATOR = "aitc-rem"


def render_document(ir: IRDocument, *, generated_on: str | None = None) -> dict[str, str]:
    """Render every test case. Returns testCaseId -> feature text."""
    return {
        case.id: render_test_case(case, ir=ir, generated_on=generated_on) for case in ir.testCases
    }


def render_test_case(
    case: TestCaseIR,
    *,
    ir: IRDocument | None = None,
    generated_on: str | None = None,
) -> str:
    lines: list[str] = []
    date = generated_on or (ir.createdAt.date().isoformat() if ir else "")

    lines.append(f"# Generated by {GENERATOR} from recording {case.recordingId} - {date}")
    if case.objective:
        lines.append(f"# Objective: {case.objective}")
    if any(_needs_review(s) for s in case.steps):
        lines.append("# Steps marked !! need human review.")
    if case.warnings:
        for warning in case.warnings[:6]:
            lines.append(f"# {warning.severity.value}: {warning.message}")
    lines.append("")

    if case.tags:
        lines.append(" ".join(f"@{t.lstrip('@')}" for t in case.tags))
    lines.append(f"Feature: {_one_line(case.title)}")

    if case.description and case.description != case.title:
        for line in case.description.splitlines():
            lines.append(f"{INDENT}{line}")
    lines.append("")

    shared = [p for p in case.preconditions if p.shared] or case.preconditions
    if shared:
        lines.append(f"{INDENT}Background:")
        for index, precondition in enumerate(shared):
            keyword = "Given" if index == 0 else "And"
            lines.append(f"{INDENT * 2}{keyword} {_one_line(precondition.text)}")
        lines.append("")

    lines.append(f"{INDENT}Scenario: {_one_line(_scenario_name(case))}")
    lines.extend(_render_steps(case))

    # Nothing is silently discarded: pruned work is marked where it happened
    # so the reader knows the narrative is not the whole session (SS9.3).
    for omitted in case.omitted:
        anchor = f" after {omitted.afterStepId}" if omitted.afterStepId else ""
        lines.append("")
        lines.append(
            f"{INDENT}# {omitted.eventCount} {omitted.reason.value} action(s) omitted"
            f"{anchor} - {_one_line(omitted.summary)}. See the review UI."
        )

    if case.parameters:
        lines.append("")
        lines.append(f"{INDENT}# Parameters (from redaction - supply real values before running):")
        for parameter in case.parameters:
            lines.append(f"{INDENT}#   {parameter.placeholder}  ({parameter.category})")

    # SS9.8 -- suggestions are strictly quarantined: never rendered as steps,
    # never exported as test cases, always labelled unverified.
    if case.suggestions:
        lines.append("")
        lines.append(f"{INDENT}# Coverage suggestions - UNVERIFIED, not part of this test:")
        for suggestion in case.suggestions:
            lines.append(f"{INDENT}#   - {_one_line(suggestion.text)}")

    return "\n".join(lines).rstrip() + "\n"


def _render_steps(case: TestCaseIR) -> list[str]:
    lines: list[str] = []
    previous_keyword: str | None = None

    for step in case.steps:
        keyword = step.keyword.value
        # `And` only reads correctly after a step of the same kind.
        if keyword == "And" and previous_keyword is None:
            keyword = "When"
        previous_keyword = keyword

        marker = " !!" if _needs_review(step) else ""
        lines.append(f"{INDENT * 2}{keyword} {_one_line(step.text)}{marker}")
        lines.extend(_evidence_comments(step))

        for assertion in step.assertions:
            if not assertion.accepted:
                continue
            lines.append(f"{INDENT * 2}Then {_one_line(assertion.text)}")
            lines.append(
                f"{INDENT * 3}# evidence: {assertion.evidence.eventId} - "
                f"{assertion.evidence.toolCallId} - {assertion.provenance.value} - "
                f"{_one_line(assertion.evidence.literal)!r}"
            )
            previous_keyword = "Then"

        if step.escalation:
            lines.append(f"{INDENT * 3}# ?? {_one_line(step.escalation)}")
        for note in step.criticNotes or []:
            lines.append(f"{INDENT * 3}# critic: {_one_line(note)}")
        lines.append("")

    return lines


def _evidence_comments(step: Step) -> list[str]:
    """Traceability lines. Selectors go here, never into step text."""
    lines: list[str] = []
    parts = [", ".join(step.eventIds)]
    if step.confidence.value != "high":
        parts.append(f"confidence: {step.confidence.value}")
    for flag in step.fidelity:
        parts.append(f"!{flag.value}")
    lines.append(f"{INDENT * 3}# {' - '.join(parts)}")

    for hint in step.selectorHints or []:
        lines.append(f"{INDENT * 3}# selector ({hint.strategy.value}): {hint.value}")
    if step.libraryRef:
        lines.append(f"{INDENT * 3}# reused from step library: {step.libraryRef}")
    return lines


def _needs_review(step: Step) -> bool:
    return bool(step.escalation) or step.confidence.value == "low" or bool(step.fidelity)


def _scenario_name(case: TestCaseIR) -> str:
    if case.description and case.description != case.title:
        return case.description.splitlines()[0]
    return case.title


def _one_line(text: str) -> str:
    """Gherkin is line-oriented; a newline inside a step would break the file."""
    return " ".join((text or "").split())
