"""The evidence sidecar -- `<case>.trace.md`, written beside the feature file.

SS3.2 makes a claim admissible only if it can point at the retrieval that
produced it. That is enforced by `evidence_retrieved` against `trace.json`, and
it is *shown* here.

The two jobs used to be one file. Every step in the `.feature` carried its event
ids and fidelity flags in a comment, which made the audit trail visible and the
test case unreadable, and the test case is what gets judged. So the body of the
feature is now prose a QA lead would have written, and everything else lands
here: what the agent did not know, what it went and looked at, what it found,
and which retrieval licenses each expected result.

SS13.3's "why this step" panel renders the same material for a human. Until the
review UI exists, this is that panel.
"""

from __future__ import annotations

from server.config import ProjectConfig
from server.models import (
    AgentTrace,
    Assertion,
    IRDocument,
    Step,
    StepInvestigation,
    TestCaseIR,
)
from server.pipeline.narrative import build_narrative
from server.renderers.gherkin import GENERATOR, feature_filename, needs_review

#: SS6.8 -- what the recorder could not determine, in the words a tester needs
#: rather than the enum's.
FIDELITY_NOTES = {
    "canvas_interaction": "the click landed on a canvas; only coordinates are known",
    "no_accessible_name": "the element has no label, so this description may be wrong",
    "closed_shadow_root": "part of this component was not readable",
    "cross_origin_frame_blocked": "an embedded frame was not accessible",
    "drag_interaction": "a drag was detected; the description is lower confidence",
    "file_content_omitted": "a file was selected but its contents were not captured",
    "rapid_sequence": "these actions were too fast to attribute to separate intents",
    "settle_timeout": "the page never quiesced, so the captured outcome may be incomplete",
    "network_incomplete": "some requests may have been missed",
}


def render_document(
    ir: IRDocument,
    *,
    trace: AgentTrace | None = None,
    generated_on: str | None = None,
    config: ProjectConfig | None = None,
) -> dict[str, str]:
    """Render a sidecar per test case. Returns testCaseId -> markdown."""
    return {
        case.id: render_trace(case, ir=ir, trace=trace, generated_on=generated_on, config=config)
        for case in ir.testCases
    }


def render_trace(
    case: TestCaseIR,
    *,
    ir: IRDocument | None = None,
    trace: AgentTrace | None = None,
    generated_on: str | None = None,
    config: ProjectConfig | None = None,
) -> str:
    config = config or ProjectConfig()
    date = generated_on or (ir.createdAt.date().isoformat() if ir else "")
    narrative = build_narrative(case.steps)
    investigations = _by_step(trace)

    out: list[str] = []
    out.append(f"# {case.title} - evidence")
    out.append("")
    provenance = f"Recording `{case.recordingId}`, run `{case.runId}`"
    if date:
        provenance += f", {date}"
    out.append(f"{provenance}. Generated by {GENERATOR}.")
    out.append(f"Feature file: `{feature_filename(case, config)}`")
    if case.objective:
        out.append("")
        out.append(f"> **Objective as stated by the tester:** {case.objective}")

    out.extend(_expected_results(case))
    out.extend(_steps(case, narrative, investigations))
    out.extend(_parameters(case))
    out.extend(_omitted(case))
    out.extend(_suggestions(case))
    out.extend(_warnings(case))

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------


def _expected_results(case: TestCaseIR) -> list[str]:
    """Every candidate, accepted or not.

    SS9.5 gives each step two or three ranked proposals rather than one, and the
    review UI turns them into checkboxes. Until that UI exists this table is how
    a tester sees the alternatives -- showing only the accepted one would hide
    the choice that was made on their behalf.
    """
    rows: list[tuple[str, Assertion]] = [
        (step.id, assertion) for step in case.steps for assertion in step.assertions
    ]

    out = ["", "## Expected results", ""]
    if not rows:
        out.append(
            "This test case asserts nothing. Every step describes an action and none "
            "of them produced an outcome the recorder could ground, so there is "
            "nothing here to verify."
        )
        return out

    out.append("| | Step | Expected result | Literal | Retrieved by | Provenance |")
    out.append("|---|---|---|---|---|---|")
    for step_id, assertion in rows:
        mark = "x" if assertion.accepted else " "
        out.append(
            f"| [{mark}] | `{step_id}` | {assertion.text} | "
            f"`{_escape(assertion.evidence.literal)}` | "
            f"`{assertion.evidence.toolCallId}` | {assertion.provenance.value} |"
        )
    out.append("")
    out.append(
        "Each row resolves: `evidence_retrieved` looks up the tool call, re-hashes "
        "the stored response and confirms the literal occurs in it. A row that did "
        "not resolve would not have been rendered (SS3.2)."
    )

    unchecked = [a for _, a in rows if not a.accepted]
    if unchecked:
        out.append("")
        out.append(
            f"{len(unchecked)} candidate(s) are unchecked: proposed, grounded, and "
            "not currently part of the test. `annotated` and `narrated` outrank "
            "`inferred`, because the first two are the tester saying what mattered "
            "and the last is the agent working it out."
        )
    return out


def _steps(
    case: TestCaseIR, narrative, investigations: dict[str, list[StepInvestigation]]
) -> list[str]:
    out = ["", "## Steps", ""]
    index = 0
    for line in narrative.body:
        if line.is_assertion or line.step is None:
            continue
        index += 1
        step = line.step
        out.append(f"### {index}. {line.keyword} {line.text}")
        out.append("")
        out.extend(_step_facts(step))

        for investigation in investigations.get(step.id, []):
            out.extend(_why(investigation))
        out.append("")
    return out


def _by_step(trace: AgentTrace | None) -> dict[str, list[StepInvestigation]]:
    """Every investigation about a step, from every stage that had one.

    Keyed on `stepId` rather than on the step's `investigationRef`, which names
    only the naming stage's. The assertion stage investigates the same step
    separately, and its record is the one that answers the question a reader
    actually has -- why does this step have no expected result?
    """
    out: dict[str, list[StepInvestigation]] = {}
    for investigation in trace.investigations if trace else []:
        if investigation.stepId:
            out.setdefault(investigation.stepId, []).append(investigation)
    return out


def _step_facts(step: Step) -> list[str]:
    facts = [f"Events: {', '.join(step.eventIds)}"]
    if step.role is not None:
        facts.append(f"Role: {step.role.value}")
    facts.append(f"Confidence: {step.confidence.value}")
    if needs_review(step):
        facts.append("**needs review**")

    out = [" | ".join(facts)]

    for flag in step.fidelity:
        note = FIDELITY_NOTES.get(flag.value, flag.value)
        out.append("")
        out.append(f"- `{flag.value}` - {note}")

    if step.escalation:
        out.append("")
        out.append(f"**The agent has a question:** {step.escalation}")

    if step.selectorHints:
        out.append("")
        out.append("Selectors, for whoever automates this later:")
        for hint in step.selectorHints:
            out.append(f"- `{hint.strategy.value}`: `{hint.value}` ({hint.stability.value})")

    if step.libraryRef:
        out.append("")
        out.append(f"Reused verbatim from step library entry `{step.libraryRef}`.")

    for note in step.criticNotes or []:
        out.append("")
        out.append(f"Critic: {note}")

    return out


def _why(investigation: StepInvestigation) -> list[str]:
    """SS13.3 -- what the agent did not know, what it looked at, why it stopped.

    A tester who sees that the tool went and looked accepts the output. A
    confident sentence with no provenance gets doubted, and rightly.
    """
    label = {
        "name": "Why this step reads as it does",
        "assert": "Why this expected result, or none",
    }.get(investigation.stage.value, f"Why ({investigation.stage.value})")

    out = ["", f"<details><summary>{label}</summary>", ""]
    if investigation.initialUncertainty:
        out.append("Could not determine up front:")
        for item in investigation.initialUncertainty:
            out.append(f"- {item}")
        out.append("")
    for entry in investigation.narrative or []:
        out.append(f"- {entry}")
    out.append("")
    out.append(
        f"Stopped because: `{investigation.stopReason.value}` "
        f"({investigation.budgetUsed} of {investigation.budgetMax} retrievals used)."
    )
    if investigation.stopRationale:
        out.append("")
        out.append(investigation.stopRationale)
    out.append("")
    out.append("</details>")
    return out


def _parameters(case: TestCaseIR) -> list[str]:
    if not case.parameters:
        return []
    out = ["", "## Parameters", ""]
    out.append(
        "Redaction replaced these in the browser, before anything was written to "
        "disk (SS7). Supply real values before running the test."
    )
    out.append("")
    out.append("| Placeholder | Category | Description |")
    out.append("|---|---|---|")
    for parameter in case.parameters:
        out.append(
            f"| `{parameter.placeholder}` | {parameter.category} | {parameter.description or ''} |"
        )
    return out


def _omitted(case: TestCaseIR) -> list[str]:
    if not case.omitted:
        return []
    out = ["", "## Omitted from the narrative", ""]
    out.append(
        "Kept here rather than deleted: a verbatim transcript is unusable and a "
        "silent deletion is untrustworthy (SS9.3)."
    )
    out.append("")
    for omitted in case.omitted:
        anchor = f" after `{omitted.afterStepId}`" if omitted.afterStepId else ""
        out.append(
            f"- **{omitted.reason.value}**{anchor}, {omitted.eventCount} action(s): "
            f"{omitted.summary}"
        )
    return out


def _suggestions(case: TestCaseIR) -> list[str]:
    """SS9.8 -- a prompt for the tester, never an artifact.

    Quarantined here rather than in the feature file, which is the strongest
    form of the separation the spec asks for: a suggestion cannot be mistaken
    for a step if it is not in the file the steps live in.
    """
    if not case.suggestions:
        return []
    out = ["", "## Coverage suggestions - UNVERIFIED", ""]
    out.append(
        "Not part of this test case and not grounded in a retrieval. These are "
        "things the recording revealed about the application that nothing has "
        "exercised yet."
    )
    out.append("")
    for suggestion in case.suggestions:
        out.append(f"- **{suggestion.category.value}** - {suggestion.text}")
        if suggestion.rationale:
            out.append(f"  - {suggestion.rationale}")
    return out


def _warnings(case: TestCaseIR) -> list[str]:
    if not case.warnings:
        return []
    out = ["", "## Warnings", ""]
    for warning in case.warnings:
        where = f" (`{warning.stepId}`)" if warning.stepId else ""
        out.append(f"- **{warning.severity.value}** {warning.message}{where}")
    return out


def _escape(text: str) -> str:
    """A literal is quoted verbatim; a pipe in it would break the table."""
    return " ".join(text.split()).replace("|", "\\|")


__all__ = ["render_document", "render_trace"]
